// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {console2} from "forge-std/console2.sol";

import {BinaryMembershipV4} from "../src/BinaryMembershipV4.sol";

interface ISafeLike {
    function getOwners() external view returns (address[] memory);
    function getThreshold() external view returns (uint256);
}

/// @title BSC mainnet deployment for the fixed-fee USDT membership contract
/// @notice Deploys V4 only. Stage configuration is intentionally a separate
///         admin action generated by ConfigureBscMainnet.s.sol.
contract DeployBscMainnet is Script {
    struct DeploymentInputs {
        address admin;
        address operator;
        address treasury;
        address company;
        address pauser;
        address root;
        uint48 adminDelay;
    }

    address internal constant BSC_USDT = 0x55d398326f99059fF775485246999027B3197955;
    bytes32 internal constant EXPECTED_USDT_RUNTIME_HASH =
        0x97a48aa4c129657440dafdacd4c836389734d28cc4a0ca7403e68da660a74a59;
    uint256 internal constant BSC_MAINNET = 56;
    uint48 internal constant MIN_ADMIN_DELAY = 10 minutes;
    bytes32 internal constant DEPLOY_SALT = keccak256("BinaryMembershipV4:BSC_MAINNET:USDT:V4");
    bytes32 internal constant ROLE_MANIFEST_DOMAIN = keccak256("BinaryMembershipV4:BSC_MAINNET:ROLE_MANIFEST:V4");

    function run() external returns (BinaryMembershipV4 membership) {
        require(block.chainid == BSC_MAINNET, "not BSC mainnet (expected chain 56)");

        uint256 deployerKey = vm.envUint("DEPLOYER_PRIVATE_KEY");
        address deployer = vm.addr(deployerKey);
        DeploymentInputs memory inputs = _readDeploymentInputs();
        address expected = vm.envAddress("EXPECTED_MEMBERSHIP_ADDRESS");
        bytes32 expectedRoleManifest = vm.envBytes32("EXPECTED_ROLE_MANIFEST_HASH");
        bool allowEoaRoles = vm.envOr("ALLOW_EOA_ROLES", false);
        bool allowSharedControl = vm.envOr("ALLOW_SHARED_CONTROL_ADDRESS", false);

        require(deployer == vm.envAddress("DEPLOYER_ADDRESS"), "deployer key/address mismatch");
        _checkInputs(inputs, deployer, allowEoaRoles, allowSharedControl);
        bytes32 roleManifest = _roleManifestHash(inputs);
        require(
            roleManifest == expectedRoleManifest && roleManifest != bytes32(0),
            "role manifest does not match expected hash"
        );

        IERC20Metadata token = _checkToken();
        address predicted = _predictAddress(address(token), inputs);
        require(expected != address(0) && predicted == expected, "predicted address does not match expected address");
        require(predicted.code.length == 0, "canonical address already has code");
        console2.log("predicted address", predicted);

        vm.startBroadcast(deployerKey);
        membership = new BinaryMembershipV4{salt: DEPLOY_SALT}(
            token, inputs.treasury, inputs.company, inputs.admin, inputs.adminDelay, inputs.root
        );
        vm.stopBroadcast();

        require(address(membership) == predicted, "CREATE2 address mismatch");
        _logDeployment(membership, token, inputs, roleManifest);
    }

    /// @notice Print the two values which must be copied into .env before run().
    ///         No private key is read and no transaction is sent.
    function predictFromEnv() external view returns (address predicted) {
        require(block.chainid == BSC_MAINNET, "not BSC mainnet (expected chain 56)");
        DeploymentInputs memory inputs = _readDeploymentInputs();
        bool allowEoaRoles = vm.envOr("ALLOW_EOA_ROLES", false);
        bool allowSharedControl = vm.envOr("ALLOW_SHARED_CONTROL_ADDRESS", false);
        _checkInputs(inputs, vm.envAddress("DEPLOYER_ADDRESS"), allowEoaRoles, allowSharedControl);
        _checkToken();

        predicted = _predictAddress(BSC_USDT, inputs);
        console2.log("canonical predicted address", predicted);
        console2.log("CREATE2 salt");
        console2.logBytes32(DEPLOY_SALT);
        console2.log("role manifest hash");
        console2.logBytes32(_roleManifestHash(inputs));
    }

    function _readDeploymentInputs() internal view returns (DeploymentInputs memory inputs) {
        inputs.admin = vm.envAddress("ADMIN_ADDRESS");
        inputs.operator = vm.envAddress("OPERATOR_ADDRESS");
        inputs.treasury = vm.envAddress("TREASURY_ADDRESS");
        inputs.company = vm.envAddress("COMPANY_WALLET_ADDRESS");
        inputs.pauser = vm.envAddress("PAUSER_ADDRESS");
        inputs.root = vm.envAddress("ROOT_ADDRESS");
        inputs.adminDelay = _checkedAdminDelay(vm.envUint("ADMIN_DELAY_SECONDS"));
    }

    function _checkInputs(DeploymentInputs memory inputs, address deployer, bool allowEoaRoles, bool allowSharedControl)
        internal
        view
    {
        _checkRoles(
            inputs.admin,
            inputs.operator,
            inputs.treasury,
            inputs.pauser,
            inputs.root,
            allowEoaRoles,
            allowSharedControl
        );
        _checkCompanyWallet(inputs.company, inputs.treasury, inputs.root);
        _checkDeployer(
            deployer, inputs.admin, inputs.operator, inputs.treasury, inputs.pauser, inputs.root, allowSharedControl
        );
    }

    /// @dev These small guards are deliberately separated so production policy
    ///      remains individually testable outside of an RPC environment.
    function _checkRoles(
        address admin,
        address operator,
        address treasury,
        address pauser,
        address root,
        bool allowEoaRoles,
        bool allowSharedControl
    ) internal view {
        require(admin != address(0), "admin is zero");
        require(operator != address(0), "operator is zero");
        require(treasury != address(0), "treasury is zero");
        require(pauser != address(0), "pauser is zero");
        require(root != address(0), "root is zero");
        require(admin != treasury, "admin and treasury must differ");
        require(operator != treasury, "operator and treasury must differ");
        require(treasury != pauser, "treasury and pauser must differ");
        if (allowSharedControl) {
            require(admin == operator && admin == pauser, "shared control requires admin=operator=pauser");
        } else {
            require(admin != operator, "admin and operator must differ");
            require(admin != pauser, "admin and pauser must differ");
            require(operator != pauser, "operator and pauser must differ");
        }
        require(root != admin, "root and admin must differ");
        require(root != operator, "root and operator must differ");
        require(root != treasury, "root and treasury must differ");
        require(root != pauser, "root and pauser must differ");
        if (!allowEoaRoles) {
            _checkSafeLike(admin, "admin");
            _checkSafeLike(operator, "operator");
            _checkSafeLike(treasury, "treasury");
            _checkSafeLike(pauser, "pauser");
        }
    }

    function _checkSafeLike(address account, string memory label) internal view {
        require(account.code.length > 0, string.concat(label, " is an EOA - use a multisig or set ALLOW_EOA_ROLES"));
        address[] memory owners;
        uint256 threshold;
        try ISafeLike(account).getOwners() returns (address[] memory configuredOwners) {
            owners = configuredOwners;
        } catch {
            revert(string.concat(label, " is not a Safe-like multisig"));
        }
        try ISafeLike(account).getThreshold() returns (uint256 configuredThreshold) {
            threshold = configuredThreshold;
        } catch {
            revert(string.concat(label, " is not a Safe-like multisig"));
        }
        require(owners.length >= 2, string.concat(label, " multisig needs at least two owners"));
        require(threshold >= 2, string.concat(label, " multisig threshold must be at least two"));
        require(threshold <= owners.length, string.concat(label, " multisig threshold exceeds owners"));
    }

    function _checkCompanyWallet(address company, address treasury, address root) internal pure {
        require(company != address(0), "company wallet is zero");
        require(company != treasury, "company and treasury must differ");
        require(company != root, "company and root must differ");
    }

    function _checkDeployer(
        address deployer,
        address admin,
        address operator,
        address treasury,
        address pauser,
        address root,
        bool allowSharedControl
    ) internal pure {
        require(deployer != address(0), "deployer is zero");
        require(deployer != treasury, "deployer and treasury must differ");
        require(deployer != root, "deployer and root must differ");
        if (allowSharedControl) {
            require(deployer == admin, "deployer must equal shared control address");
            require(deployer == operator, "deployer and operator mismatch");
            require(deployer == pauser, "deployer and pauser mismatch");
        } else {
            require(deployer != admin, "deployer and admin must differ");
            require(deployer != operator, "deployer and operator must differ");
            require(deployer != pauser, "deployer and pauser must differ");
        }
    }

    function _checkExpectedAddress(address predicted, address expected) internal pure {
        require(expected != address(0), "expected membership address is zero");
        require(predicted == expected, "predicted address does not match expected address");
    }

    function _checkRoleManifest(bytes32 actual, bytes32 expected) internal pure {
        require(expected != bytes32(0), "expected role manifest is zero");
        require(actual == expected, "role manifest does not match expected hash");
    }

    function _checkToken() internal view returns (IERC20Metadata token) {
        token = IERC20Metadata(BSC_USDT);
        require(BSC_USDT.code.length > 0, "USDT has no code");
        require(keccak256(BSC_USDT.code) == EXPECTED_USDT_RUNTIME_HASH, "USDT runtime hash changed");
        require(token.decimals() == 18, "USDT must have 18 decimals");
        require(token.totalSupply() > 0, "USDT has no supply");
    }

    function _predictAddress(address token, DeploymentInputs memory inputs) internal pure returns (address) {
        bytes32 initCodeHash = keccak256(
            abi.encodePacked(
                type(BinaryMembershipV4).creationCode,
                abi.encode(token, inputs.treasury, inputs.company, inputs.admin, inputs.adminDelay, inputs.root)
            )
        );
        return vm.computeCreate2Address(DEPLOY_SALT, initCodeHash);
    }

    function _roleManifestHash(DeploymentInputs memory inputs) internal pure returns (bytes32) {
        return _roleManifestHash(
            inputs.admin,
            inputs.operator,
            inputs.treasury,
            inputs.company,
            inputs.pauser,
            inputs.root,
            inputs.adminDelay
        );
    }

    function _roleManifestHash(
        address admin,
        address operator,
        address treasury,
        address company,
        address pauser,
        address root,
        uint48 adminDelay
    ) internal pure returns (bytes32) {
        return keccak256(
            abi.encode(ROLE_MANIFEST_DOMAIN, BSC_MAINNET, admin, operator, treasury, company, pauser, root, adminDelay)
        );
    }

    function _logDeployment(
        BinaryMembershipV4 membership,
        IERC20Metadata token,
        DeploymentInputs memory inputs,
        bytes32 roleManifest
    ) internal view {
        console2.log("=== V4 USDT DEPLOYED ===");
        console2.log("membership", address(membership));
        console2.log("payment token", address(token));
        console2.log("token decimals", token.decimals());
        console2.log("admin", inputs.admin);
        console2.log("admin delay (s)", inputs.adminDelay);
        console2.log("root", inputs.root);
        console2.log("treasury", inputs.treasury);
        console2.log("company", inputs.company);
        console2.log("role manifest");
        console2.logBytes32(roleManifest);
        console2.log("NOT CONFIGURED: execute the five generated admin configuration calls before launch.");
    }

    function deploymentSalt() external pure returns (bytes32) {
        return DEPLOY_SALT;
    }

    function _checkedAdminDelay(uint256 rawDelay) internal pure returns (uint48 adminDelay) {
        require(rawDelay <= type(uint48).max, "admin delay exceeds uint48");
        adminDelay = uint48(rawDelay);
        _checkAdminDelay(adminDelay);
    }

    function _checkAdminDelay(uint48 adminDelay) internal pure {
        require(adminDelay != 0, "admin delay must not be zero on mainnet");
        require(adminDelay >= MIN_ADMIN_DELAY, "admin delay below the safe floor");
    }
}
